name: Linux Composer Privilege Escalation
id: linux-composer-privilege-escalation-001
version: 1
schema_version: "1.0"
date: "2026-02-04"
author: SOCFortress LLC
status: production
type: Anomaly

description: >
  Detects the execution of the Composer tool with elevated privileges on a Linux 
  system. Identifies instances where Composer is run with sudo and run-script, 
  allowing the user to execute system commands as root. This GTFOBins technique 
  can indicate an attempt to escalate privileges, potentially leading to unauthorized 
  root access and full system compromise.

data_source:
  - auth.log
  - Tetragon
  - Linux Auditd

search:
  index_pattern: "${INDEX_PATTERN}"
  size: 100
  sort:
    - timestamp: desc
  query:
    bool:
      must:
        - term:
            agent_name: "${AGENT_NAME}"
        - term:
            agent_labels_customer: "${CUSTOMER_CODE}"
        - wildcard:
            full_log: "*composer*"
        - bool:
            should:
              - wildcard:
                  full_log: "*run-script*"
              - wildcard:
                  full_log: "*sudo*"
              - wildcard:
                  full_log: "*72756E2D736372697074*"
            minimum_should_match: 1
        - range:
            timestamp:
              gte: "${START_TIME}"
              lte: "${END_TIME}"
      must_not:
        - exists:
            field: data_win_system_eventID
        - wildcard:
            rule_groups: "*windows*"
  _source:
    - timestamp
    - agent_name
    - full_log
    - rule_mitre_id
    - rule_description
    - location

parameters:
  AGENT_NAME:
    description: "Target agent/host name"
    type: string
    required: true
    example: "Amine"
  CUSTOMER_CODE:
    description: "Customer label for filtering"
    type: string
    required: true
    example: "lab"
  START_TIME:
    description: "Query start time (ISO 8601 or relative)"
    type: datetime
    required: false
    default: "now-24h"
    example: "2026-02-04 00:00:00.000"
  END_TIME:
    description: "Query end time (ISO 8601 or relative)"
    type: datetime
    required: false
    default: "now"
    example: "2026-02-04 23:59:59.999"

how_to_implement: >
  This detection requires Wazuh agents deployed on Linux endpoints with auth.log 
  monitoring and Tetragon process execution logging enabled. Auditd provides 
  additional USER_CMD visibility with hex-encoded command arguments.

known_false_positives: >
  Developers may use composer with sudo for legitimate package management. However, 
  the run-script command combined with sudo is rarely used legitimately. Filter 
  based on known development environments and expected usage patterns.

references:
  - https://gtfobins.github.io/gtfobins/composer/
  - https://getcomposer.org/doc/00-intro.md
  - https://attack.mitre.org/techniques/T1548/003/

response:
  message: >
    Composer privilege escalation detected on $agent_name$. 
    The sudo composer run-script pattern can execute arbitrary commands as root. 
    MITRE ATT&CK: T1548.003
  risk_score: 10
  severity: low
  risk_objects:
    - field: agent_name
      type: system
      score: 10
  threat_objects: []

tags:
  analytic_story:
    - Linux Privilege Escalation
    - Linux Living Off The Land
  asset_type: Linux
  mitre_attack_id:
    - T1548.003
  product:
    - Wazuh
  security_domain: endpoint
